services:
  backend:
    build: ./Backend
    container_name: equipier_veille_backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - FLASK_ENV=production

  frontend:
    build: ./Frontend
    container_name: equipier_veille_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    restart: unless-stopped
    depends_on:
      - backend
