services:
  web:
    build: .
    container_name: equipier_veille_app
    ports:
      - "8000:8000"
    volumes:
      # Permet de lier le fichier SQLite local pour ne pas perdre les données si le conteneur s'arrête
      - ./data:/app/data
    restart: unless-stopped